apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tssc-jenkins 
  description: Secure Supply Chain Example Jenkins   
  annotations: 
    backstage.io/techdocs-ref: dir:. 
    quay.io/repository-slug: jduimovich0/bootstrap
    jenkins.io/job-full-name: john-home-jenkins/tssc-jenkins
  tags: ["jenkins"] 
spec:
  type: service
  owner: user:guest 
  lifecycle: experimental 
 
