apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  argocd/app-name: tssc-jenkins
  janus-idp.io/tekton: tssc-jenkins
  backstage.io/kubernetes-id: tssc-jenkins
  backstage.io/kubernetes-namespace: rhtap-app
  app.kubernetes.io/part-of: tssc-jenkins
resources:
- deployment.yaml
- route.yaml
- service.yaml
