---
name: Build push images

"on":
  push:
    branches:
      - main

    paths:
      # Only run if the images would change
      - "Dockerfile"
      - "rhtap/**"
      - "copy-scripts.sh"

  # ..or if manually triggered
  workflow_dispatch:

jobs:
  build-push-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install podman
        run: |
          sudo apt -y install podman

      - name: Podman login
        env:
          QUAY_USER: "${{ secrets.QUAY_PUSH_CREDS_USER }}"
          QUAY_PASS: "${{ secrets.QUAY_PUSH_CREDS_PASS }}"
        run: |
          podman login quay.io -u "${QUAY_USER}" -p "${QUAY_PASS}"

      - name: Podman build and push
        env:
          RUNNER_IMAGE_ORG: redhat-appstudio
          RUNNER_IMAGE_REPO: dance-bootstrap-app
        run: |
          make build-push-image
