---
name: Checks

"on":
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  generated-file-freshness:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install node dependencies
        run: |
          make install-deps

      - name: Confirm file freshness
        run: |
          make ensure-fresh

  script-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install shfmt
        run: |
          make install-shfmt

      - name: Confirm script formatting
        run: |
          make ensure-formatted
